[package]
name = "ownership"
version = "0.1.0"
<<<<<<< HEAD
authors = ["Phillip Shreves <hi@phillips.work>"]
=======
authors = ["Phillip Shreves <pshreves@highpointgo.com>"]
>>>>>>> f5e0e6002d42cdced00ad5ef0702e98c0fc13f2e
edition = "2018"

[dependencies]
